# Generated by Django 5.2.8 on 2025-12-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_profile',
            name='login_reference',
        ),
        migrations.DeleteModel(
            name='job_list',
        ),
        migrations.DeleteModel(
            name='employee_profile',
        ),
    ]
