# Generated by Django 5.2.8 on 2025-12-04 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_website', '0003_remove_employee_profile_profile_picture_and_more'),
        ('login_files', '0002_remove_employee_profile_login_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='google_job_hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_refrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_website.job_list')),
            ],
        ),
    ]
