# Generated by Django 5.2.8 on 2025-12-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_files', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='google_job_hire',
        ),
    ]
