# Generated by Django 5.2.8 on 2025-12-03 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='job_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=250, null=True)),
                ('job_name', models.CharField(max_length=150, null=True)),
                ('Location', models.CharField(max_length=500, null=True)),
                ('Type', models.CharField(max_length=150, null=True)),
                ('content', models.CharField(max_length=15000, null=True)),
                ('Industry', models.CharField(max_length=150, null=True)),
                ('Company_Size', models.CharField(max_length=150, null=True)),
                ('Experience', models.CharField(max_length=150, null=True)),
                ('Skills', models.CharField(max_length=150, null=True)),
                ('Description', models.CharField(max_length=15000, null=True)),
                ('Website', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('professional', models.CharField(blank=True, default='Professional', max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.CharField(blank=True, max_length=200, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('project', models.TextField(blank=True, null=True)),
                ('login_reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
