# Generated by Django 5.2.8 on 2025-12-03 07:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeProfile',
            new_name='employee_profile',
        ),
    ]
