# Generated by Django 5.2.8 on 2025-12-03 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_website', '0002_rename_employeeprofile_employee_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_profile',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='education',
            field=models.CharField(default=12, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='login_reference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='professional',
            field=models.CharField(default='you are  professional', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='project',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='work_experience',
            field=models.CharField(max_length=1000),
        ),
    ]
