# Generated by Django 5.2.8 on 2025-12-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_website', '0003_remove_employee_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
