# Generated by Django 5.2.8 on 2025-12-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_website', '0004_employee_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='image',
            field=models.ImageField(null=True, upload_to='imagaes/'),
        ),
    ]
